name: Build

on:
    push:
        branches-ignore: ['main']
        tags-ignore:
            - 'v*'
    pull_request:
    workflow_dispatch:
      inputs:
        skip_ci:
          description: 'Set to "true" to skip CI when running manually'
          required: false
          default: 'false'
    
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    if: >-
      (github.event_name == 'push' && !contains(github.event.head_commit.message || '', '[skip ci]'))
      ||
      (github.event_name == 'pull_request' &&
        !contains(github.event.pull_request.title || '', '[skip ci]') &&
        !contains(github.event.pull_request.body || '', '[skip ci]'))
      ||
      (github.event_name == 'workflow_dispatch' &&
        (github.event.inputs.skip_ci || '') != 'true')

    strategy:
      fail-fast: false
      matrix:
        node-version: [20.x, 22.x]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }} 
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Clean cache
        run: npm cache clean --force
    
      - name: Verify Node.js version
        run: node -v

      - name: Verify Npm version
        run: npm -v
            
      - name: Install dependencies
        run: npm ci
  
      - name: Build the project
        run: npm run build
